### ISSUE TITLE
Change screen border player bouncing mechanics

### ISSUE THREAD

**Issue by saarshe** [AdiHarif/Asteroids#20]
Change the weird mechanic where the player bounces off the borders of the screen
Idea: Warp to the other end of the screen (like Pacman). Mirror/Duplicate the player so it warps smoothly.

**Comment by AdiHarif** [comment]
Fixed with - 1f457259c281bf4bb81bdc3537a1ece38899b046

**Comment by AdiHarif** [comment]
Bug - Spaceship still goes off screen to the right and bottom.

**Comment by AdiHarif** [comment]
Fixed by - 4ed6bec172a261b02ee450dfede0f27994697325
